### Test API
GET http://localhost:3000/

### Create new vehicule
POST http://localhost:3000/vehicule
Content-Type: application/json

{
    "brand": "audi",
    "model": "A4",
    "licensePlate": "AB123CD",
    "year": 2019,
    "rentalPrice": 15000
}

### Get all vehicules
GET http://localhost:3000/vehicules


### Update vehicule
PUT http://localhost:3000/vehicule/8d11f7aa-4089-4a57-9719-6cf469e6da24
Content-Type: application/json

{
    "brand": "vvv",
    "model": "Passat",
    "licensePlate": "TZ053EQ",
    "year": 2018,
    "rentalPrice": 50000
}

### Delete vehicule
DELETE http://localhost:3000/vehicule/8d11f7aa-4089-4a57-9719-6cf469e6da24


### Get vehicule by ID
GET http://localhost:3000/vehicule/fa7e847b-5796-45ab-8590-4bc0fd6484d6


### Search vehicule by registration
GET http://localhost:3000/vehicule/search/SG057PP

### Get vehicules by price
GET http://localhost:3000/vehicule/price/50000


