### Test API
GET http://localhost:3000/

### Create new vehicule
POST http://localhost:3000/vehicule
Content-Type: application/json

{
    "brand": "audi",
    "model": "A4",
    "licensePlate": "AB123CD",
    "year": 2019,
    "rentalPrice": 15000
}

### Get all vehicules
GET http://localhost:3000/vehicules


### Update vehicule
PUT http://localhost:3000/vehicule/beed96ef-45ac-44cb-8130-722455206f7c
Content-Type: application/json

{
    "brand": "vvv",
    "model": "Passat",
    "licensePlate": "TZ053EQ",
    "year": 2018,
    "rentalPrice": 50000
}

### Delete vehicule
DELETE http://localhost:3000/vehicule/beed96ef-45ac-44cb-8130-722455206f7c


### Get vehicule by ID
GET http://localhost:3000/vehicule/9064e6c4-9e7f-4092-bff6-f16212381252


### Search vehicule by registration
GET http://localhost:3000/vehicule/search/IE503DM

### Get vehicules by price
GET http://localhost:3000/vehicule/price/50000


