### Test API
GET http://localhost:3000/

### Create new vehicule
POST http://localhost:3000/vehicule
Content-Type: application/json

{
    "brand": "audi",
    "model": "A4",
    "licensePlate": "AB123CD",
    "year": 2019,
    "rentalPrice": 15000
}

### Get all vehicules
GET http://localhost:3000/vehicules


### Update vehicule
PUT http://localhost:3000/vehicule/67a4bb27676e9ce14a6224ca
Content-Type: application/json

{
    "brand": "audi",
    "model": "A4",
    "licensePlate": "TZ053EQ",
    "year": 2018,
    "rentalPrice": 50000
}

### Delete vehicule
DELETE http://localhost:3000/vehicule/67a4ba4fa197f9ddd7709fd6


### Get vehicule by ID
GET http://localhost:3000/vehicule/67a4bb27676e9ce14a6224ca


### Search vehicule by registration
GET http://localhost:3000/vehicule/search/AB123CD

### Get vehicules by price
GET http://localhost:3000/vehicule/price/50000


